In [1]:
from sklearn import datasetstasets

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris = datasets.load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [9]:
#Extracting first 100 samples pertainig to iris setosa and verginica
X = iris.data[:100,:4]

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
Y = iris.target[:100]

In [8]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Normalising the dataset

In [10]:
import numpy as np
def normalize(data):
    col_max = np.max(data,axis=0)
    col_min = np.min(data,axis=0)
    return np.divide(data-col_min,col_max-col_min)
X_norm = normalize(X)

# Getting Dimension Right

In [14]:
X_norm
X_data = X_norm.T
X_data.shape

(4, 100)

In [15]:
Y_data = Y.reshape(1,100)

In [16]:
Y_data.shape

(1, 100)

# Initialising Weights ans Bias

In [18]:
# since we have four features, we need to have weight vector of shape(4,1) and one bias term (1,1)

def initialiseNetwork(num_features):
    W = np.zeros((num_features,1))
    b=0
    parameters = {"W":W,"b":b}
    return parameters


# Defining Activation Function

In [19]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

# Forward Propagation

In [20]:
def forwardPropagation(X,Y,parameters):
    W = parameters["W"]
    b = parameters["b"]
    Z = np.dot(W.T,X)+b
    A = sigmoid(Z)
    return A

# Calculating Cost Function for a given number of samples

In [21]:
def cost(A,Y,num_samples):
    return -1/num_samples*np.sum(Y*np.log(A)+(1-Y)*(np.log(1-A)))

# Backward Propagration

In [22]:
def backPropagration(X,Y,A,num_samples):
    dZ = A-Y
    dW = (np.dot(X,dZ.T))/num_samples
    db = np.sum(dZ)/num_samples
    return dW,db

# Updating Parameters

In [23]:
def updateParameters(parameters,dW,db,learning_rate):
    W = parameters["W"]-(learning_rate*dW)
    b = parameters["b"]-(learning_rate*db)
    return {"W":W,"b":b}

# Defining Model

In [24]:
def model(X,Y,num_iter,learning_rate):
    num_features = X.shape[0]
    num_samples = float(X.shape[1])
    parameters = initialiseNetwork(num_features)
    for i in range(num_iter):
        A = forwardPropagation(X,Y,parameters)
        if(i%100==0):
            print("cost after {} iteration : {}".format(i,cost(A,Y,num_samples)))
        dW,db = backPropagration(X,Y,A,num_samples)
        parameters = updateParameters(parameters,dW,db,learning_rate)
    return parameters

# Training The Model

In [43]:
parameters = model(X_data,Y_data,2000,0.1)

cost after 0 iteration : 0.6931471805599453
cost after 100 iteration : 0.36066502331205713
cost after 200 iteration : 0.23412895775986442
cost after 300 iteration : 0.17107626682520688
cost after 400 iteration : 0.1342602622750863
cost after 500 iteration : 0.11036629293513053
cost after 600 iteration : 0.0936828865533022
cost after 700 iteration : 0.08140160958992804
cost after 800 iteration : 0.07199406438870272
cost after 900 iteration : 0.06456167935226495
cost after 1000 iteration : 0.058543271498550924
cost after 1100 iteration : 0.05357098929144816
cost after 1200 iteration : 0.04939397721464147
cost after 1300 iteration : 0.045835440515248654
cost after 1400 iteration : 0.042767268951004786
cost after 1500 iteration : 0.040094398133502365
cost after 1600 iteration : 0.03774482133713045
cost after 1700 iteration : 0.035663010203131416
cost after 1800 iteration : 0.03380546261926598
cost after 1900 iteration : 0.03213761779498093


You can see after every 100 iteration cost has been reduced

In [44]:
parameters

{'W': array([[ 1.56554819],
        [-3.69383223],
        [ 4.67258198],
        [ 4.39365947]]), 'b': -2.6063812530052672}

In [62]:
prediction = forwardPropagation(X_data,Y_data,parameters)

In [63]:
prediction

array([[0.02327448, 0.04380281, 0.02605824, 0.03566874, 0.01891431,
        0.03490018, 0.02622661, 0.0285549 , 0.03844686, 0.03287355,
        0.02282627, 0.02849944, 0.03230484, 0.01743798, 0.01301639,
        0.01562293, 0.0224096 , 0.02993318, 0.03731501, 0.02132831,
        0.04448526, 0.03186693, 0.00959819, 0.09015197, 0.03965555,
        0.05746743, 0.0523472 , 0.02752099, 0.02861046, 0.03629444,
        0.04447948, 0.05851793, 0.00860467, 0.01012789, 0.04215993,
        0.02762466, 0.02611253, 0.01385476, 0.02968013, 0.03020805,
        0.02532416, 0.1097452 , 0.02198924, 0.0735702 , 0.04262114,
        0.05301045, 0.01851208, 0.02751735, 0.02156811, 0.02968405,
        0.99088637, 0.98752467, 0.99488849, 0.98445054, 0.9942856 ,
        0.98311505, 0.99049076, 0.88826491, 0.98950399, 0.97077172,
        0.95141761, 0.98283308, 0.97846978, 0.99032711, 0.94410284,
        0.98696366, 0.98544848, 0.95456543, 0.99696523, 0.96329177,
        0.99450704, 0.97648703, 0.99711889, 0.98

We can see the predicting values are nearly to its original values

# Converting all values to categorical values 0 & 1 

In [67]:
type(prediction)
prediction.shape

(1, 100)

In [72]:
pred = np.where(prediction>0.1,1,0)

In [73]:
pred

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [91]:
Y_data

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])